Repository codesquad-member-2020/baseball-11, pull requests merged in 2020-05, with the labels that each got.

#2 [Team] 이슈 및 PR 템플릿 추가
  .github/ISSUE_TEMPLATE/-be--title.md
  .github/ISSUE_TEMPLATE/-fe--title.md
  .github/ISSUE_TEMPLATE/-ios--title.md
  .github/ISSUE_TEMPLATE/-team--title.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#8 [FE] 프로젝트 초기 세팅
  FE/client/.gitignore
  FE/client/README.md
  FE/client/package.json
  FE/client/public/index.html
  FE/client/src/App.js
  FE/client/src/index.js
  FE/client/src/serviceWorker.js
Labels: FE

#11 [FE] 게임 선택 화면 구현
  FE/client/.gitignore
  FE/client/package.json
  FE/client/public/images/ground.jpg
  FE/client/public/images/main-background.jpg
  FE/client/public/images/mario.png
  FE/client/src/App.js
  FE/client/src/components/main/Main.jsx
  FE/client/src/components/match/Match.jsx
  FE/client/src/components/select/Select.jsx
  FE/client/src/utils/useFetch.js
Labels: FE

#13 [iOS] 야구 그라운드 뷰 구현
  iOS/.gitignore
  iOS/Baseball/Baseball.xcodeproj/project.pbxproj
  iOS/Baseball/Baseball.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/Baseball/Baseball.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Baseball/Baseball/AppDelegate.swift
  iOS/Baseball/Baseball/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Baseball/Baseball/Assets.xcassets/Contents.json
  iOS/Baseball/Baseball/Assets.xcassets/backgroundGreen.colorset/Contents.json
  iOS/Baseball/Baseball/Assets.xcassets/ballGreen.colorset/Contents.json
  iOS/Baseball/Baseball/Assets.xcassets/baseYellow.colorset/Contents.json
  iOS/Baseball/Baseball/Assets.xcassets/borderDarkGreen.colorset/Contents.json
  iOS/Baseball/Baseball/Assets.xcassets/borderGreen.colorset/Contents.json
  iOS/Baseball/Baseball/Assets.xcassets/grass.imageset/Contents.json
  iOS/Baseball/Baseball/Assets.xcassets/grass.imageset/grass@2x.png
  iOS/Baseball/Baseball/Assets.xcassets/outRed.colorset/Contents.json
  iOS/Baseball/Baseball/Assets.xcassets/strikeYellow.colorset/Contents.json
  iOS/Baseball/Baseball/Base.lproj/LaunchScreen.storyboard
  iOS/Baseball/Baseball/Base.lproj/Main.storyboard
  iOS/Baseball/Baseball/FirstViewController.swift
  iOS/Baseball/Baseball/Info.plist
  iOS/Baseball/Baseball/SceneDelegate.swift
  iOS/Baseball/Baseball/SecondViewController.swift
  iOS/Baseball/Baseball/Utils/UIColorExtensions.swift
  iOS/Baseball/Baseball/Views/GameplayView.swift
  iOS/Baseball/BaseballTests/BaseballTests.swift
  iOS/Baseball/BaseballTests/Info.plist
  iOS/README.md
Labels: iOS

#17 [FE] 게임 화면 구현
  FE/client/.gitignore
  FE/client/public/images/ground.jpg
  FE/client/public/images/main-background.jpg
  FE/client/public/images/mario.png
  FE/client/src/App.js
  FE/client/src/components/NotFound.jsx
  FE/client/src/components/main/Main.jsx
  FE/client/src/components/match/Match.jsx
  FE/client/src/components/match/ground/GameButtons.jsx
  FE/client/src/components/match/ground/Ground.jsx
  FE/client/src/components/match/ground/Player.jsx
  FE/client/src/components/match/matchLog/LogDetail.jsx
  FE/client/src/components/match/matchLog/MatchLog.jsx
  FE/client/src/components/match/scoreBoard/BottomBoard.jsx
  FE/client/src/components/match/scoreBoard/ScoreBoard.jsx
  FE/client/src/components/match/scoreBoard/TopBoard.jsx
  FE/client/src/components/select/Games.jsx
  FE/client/src/components/select/Select.jsx
  FE/client/src/styles/GlobalStyle.js
  FE/client/src/utils/useSound.js
Labels: FE

#18 [FE] 야구 게임 1주차 기능 구현
  FE/client/.gitignore
  FE/client/README.md
  FE/client/package.json
  FE/client/public/index.html
  FE/client/src/App.js
  FE/client/src/components/NotFound.jsx
  FE/client/src/components/main/Main.jsx
  FE/client/src/components/match/Match.jsx
  FE/client/src/components/match/ground/GameButtons.jsx
  FE/client/src/components/match/ground/Ground.jsx
  FE/client/src/components/match/ground/Player.jsx
  FE/client/src/components/match/matchLog/LogDetail.jsx
  FE/client/src/components/match/matchLog/MatchLog.jsx
  FE/client/src/components/match/scoreBoard/BottomBoard.jsx
  FE/client/src/components/match/scoreBoard/ScoreBoard.jsx
  FE/client/src/components/match/scoreBoard/TopBoard.jsx
  FE/client/src/components/select/Games.jsx
  FE/client/src/components/select/Select.jsx
  FE/client/src/index.js
  FE/client/src/serviceWorker.js
  FE/client/src/styles/GlobalStyle.js
  FE/client/src/utils/useFetch.js
  FE/client/src/utils/useSound.js
Labels: FE

#19 Be/feature/team select
  BE/build.gradle
  BE/src/main/java/com/codesquad/baseballgame/domain/team/TeamController.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/controller/TeamController.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/dao/TeamDao.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/dto/TeamDataDto.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/dto/TeamDto.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/dto/TeamSideDto.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/mapper/TeamDtoMapper.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/service/TeamService.java
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/baseballgame/domain/team/dao/TeamDaoTest.java
Labels: BE

#23 [iOS] 매치 리스트 뷰 구현
  iOS/Baseball/Baseball.xcodeproj/project.pbxproj
  iOS/Baseball/Baseball/Base.lproj/Main.storyboard
  iOS/Baseball/Baseball/Controllers/MatchListViewController.swift
  iOS/Baseball/Baseball/Controllers/PlayViewController.swift
  iOS/Baseball/Baseball/Controllers/ScoreViewController.swift
  iOS/Baseball/Baseball/Delegates/MatchListDelegate.swift
  iOS/Baseball/Baseball/Models/Match.swift
  iOS/Baseball/Baseball/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/away.imageset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/away.imageset/away.png
  iOS/Baseball/Baseball/Resources/Assets.xcassets/backgroundGreen.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/backgroundLightBlue.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/ballGreen.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/baseYellow.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/borderDarkGreen.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/borderGreen.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/grass.imageset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/grass.imageset/grass@2x.png
  iOS/Baseball/Baseball/Resources/Assets.xcassets/home.imageset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/home.imageset/home.png
  iOS/Baseball/Baseball/Resources/Assets.xcassets/outRed.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/strikeYellow.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/SuperMario256.ttf
  iOS/Baseball/Baseball/Utils/ReusableView.swift
  iOS/Baseball/Baseball/Utils/UIColorExtensions.swift
  iOS/Baseball/Baseball/ViewModels/MatchListViewModel.swift
  iOS/Baseball/Baseball/Views/MatchCell.swift
  iOS/README.md
Labels: iOS

#26 [iOS] 매치 리스트 Mock 데이터 표시
  iOS/Baseball/Baseball.xcodeproj/project.pbxproj
  iOS/Baseball/Baseball/Base.lproj/Main.storyboard
  iOS/Baseball/Baseball/Controllers/MatchListViewController.swift
  iOS/Baseball/Baseball/Models/DefaultLocation.swift
  iOS/Baseball/Baseball/Models/Match.swift
  iOS/Baseball/Baseball/Networking/APIBuilder.swift
  iOS/Baseball/Baseball/Networking/APIRouter.swift
  iOS/Baseball/Baseball/Networking/Endpoints.swift
  iOS/Baseball/Baseball/Networking/Mocking/MatchesResponse.json
  iOS/Baseball/Baseball/Networking/Mocking/URLProtocolMock.swift
  iOS/Baseball/Baseball/Networking/NetworkManager.swift
  iOS/Baseball/Baseball/UseCases/MatchesUseCase.swift
  iOS/Baseball/Baseball/ViewModels/MatchListViewModel.swift
  iOS/Baseball/Baseball/Views/DimView.swift
  iOS/Baseball/Baseball/Views/MatchCell.swift
  iOS/README.md
  iOS/result1.png
Labels: iOS

#30 Be/feature/oauth login
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/com/codesquad/baseballgame/domain/team/controller/TeamController.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/dao/TeamDao.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/dto/TeamDto.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/mapper/TeamDtoMapper.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/service/TeamService.java
  BE/src/main/java/com/codesquad/baseballgame/global/config/GithubOauthProperty.java
  BE/src/main/java/com/codesquad/baseballgame/global/github/controller/GithubLoginController.java
  BE/src/main/java/com/codesquad/baseballgame/global/github/dao/UserDao.java
  BE/src/main/java/com/codesquad/baseballgame/global/github/dto/GithubToken.java
  BE/src/main/java/com/codesquad/baseballgame/global/github/dto/UserDto.java
  BE/src/main/java/com/codesquad/baseballgame/global/github/mapper/UserDtoMapper.java
  BE/src/main/java/com/codesquad/baseballgame/global/github/service/GithubLoginService.java
  BE/src/main/java/com/codesquad/baseballgame/global/utils/JwtUtils.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/baseballgame/global/github/GithubTokenLoginServiceTest.java
  BE/src/test/java/com/codesquad/baseballgame/global/github/dao/UserDaoTest.java
Labels: BE

#34 [FE] 상세 점수, 선수 명단 팝업 구현
  FE/client/src/App.js
  FE/client/src/components/NotFound.jsx
  FE/client/src/components/main/Main.jsx
  FE/client/src/components/match/Match.jsx
  FE/client/src/components/match/detailInfo/DetailInfo.jsx
  FE/client/src/components/match/detailInfo/InfoButtons.jsx
  FE/client/src/components/match/detailInfo/PlayerInfo.jsx
  FE/client/src/components/match/detailInfo/ScoreInfo.jsx
  FE/client/src/components/match/detailInfo/TPlayer.jsx
  FE/client/src/components/match/detailInfo/TScore.jsx
  FE/client/src/components/match/ground/Base.jsx
  FE/client/src/components/match/ground/GameButtons.jsx
  FE/client/src/components/match/ground/Ground.jsx
  FE/client/src/components/match/ground/Hitter.jsx
  FE/client/src/components/match/matchLog/MatchLog.jsx
  FE/client/src/components/match/scoreBoard/BottomBoard.jsx
  FE/client/src/components/match/scoreBoard/TopBoard.jsx
  FE/client/src/components/select/Games.jsx
  FE/client/src/components/select/Select.jsx
  FE/client/src/constants/url.js
  FE/client/src/hooks/useFetch.js
  FE/client/src/hooks/useSound.js
  FE/client/src/store/MatchStore.jsx
  FE/client/src/utils/dataFetch.js
  FE/client/src/utils/effectSound.js
Labels: FE

#41 [#32] 선수 명단 출력 기능 구현
  BE/src/main/java/com/codesquad/baseballgame/domain/ballcount/BallCountController.java
  BE/src/main/java/com/codesquad/baseballgame/domain/hitter/HitterController.java
  BE/src/main/java/com/codesquad/baseballgame/domain/hitter/controller/HitterController.java
  BE/src/main/java/com/codesquad/baseballgame/domain/hitter/dao/HitterDao.java
  BE/src/main/java/com/codesquad/baseballgame/domain/hitter/dto/HitterInfoDto.java
  BE/src/main/java/com/codesquad/baseballgame/domain/hitter/dto/HitterListDto.java
  BE/src/main/java/com/codesquad/baseballgame/domain/hitter/dto/HitterTeamDto.java
  BE/src/main/java/com/codesquad/baseballgame/domain/hitter/mapper/HitterListMapper.java
  BE/src/main/java/com/codesquad/baseballgame/domain/hitter/mapper/HitterMapper.java
  BE/src/main/java/com/codesquad/baseballgame/domain/hitter/service/HitterService.java
  BE/src/main/java/com/codesquad/baseballgame/domain/player/PlayerController.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/controller/TeamController.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/dao/TeamDao.java
  BE/src/main/java/com/codesquad/baseballgame/domain/team/service/TeamService.java
  BE/src/main/java/com/codesquad/baseballgame/global/github/controller/GithubLoginController.java
  BE/src/main/java/com/codesquad/baseballgame/global/github/dao/UserDao.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/baseballgame/domain/hitter/dao/HitterDaoTest.java
  BE/src/test/java/com/codesquad/baseballgame/domain/hitter/service/HitterServiceTest.java
  BE/src/test/java/com/codesquad/baseballgame/domain/team/dao/TeamDaoTest.java
Labels: BE

#25 [iOS] 매치 선택 뷰, 야구 그라운드 구현
  iOS/.gitignore
  iOS/Baseball/Baseball.xcodeproj/project.pbxproj
  iOS/Baseball/Baseball.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/Baseball/Baseball.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Baseball/Baseball/AppDelegate.swift
  iOS/Baseball/Baseball/Base.lproj/LaunchScreen.storyboard
  iOS/Baseball/Baseball/Base.lproj/Main.storyboard
  iOS/Baseball/Baseball/Controllers/MatchListViewController.swift
  iOS/Baseball/Baseball/Controllers/PlayViewController.swift
  iOS/Baseball/Baseball/Controllers/ScoreViewController.swift
  iOS/Baseball/Baseball/Delegates/MatchListLayout.swift
  iOS/Baseball/Baseball/Info.plist
  iOS/Baseball/Baseball/Models/DefaultLocation.swift
  iOS/Baseball/Baseball/Models/Match.swift
  iOS/Baseball/Baseball/Networking/APIBuilder.swift
  iOS/Baseball/Baseball/Networking/APIRouter.swift
  iOS/Baseball/Baseball/Networking/Endpoints.swift
  iOS/Baseball/Baseball/Networking/Mocking/MatchesResponse.json
  iOS/Baseball/Baseball/Networking/Mocking/URLProtocolMock.swift
  iOS/Baseball/Baseball/Networking/NetworkManager.swift
  iOS/Baseball/Baseball/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/away.imageset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/away.imageset/away.png
  iOS/Baseball/Baseball/Resources/Assets.xcassets/backgroundGreen.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/backgroundLightBlue.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/ballGreen.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/baseYellow.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/borderDarkGreen.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/borderGreen.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/grass.imageset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/grass.imageset/grass@2x.png
  iOS/Baseball/Baseball/Resources/Assets.xcassets/home.imageset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/home.imageset/home.png
  iOS/Baseball/Baseball/Resources/Assets.xcassets/outRed.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/strikeYellow.colorset/Contents.json
  iOS/Baseball/Baseball/Resources/SuperMario256.ttf
  iOS/Baseball/Baseball/SceneDelegate.swift
  iOS/Baseball/Baseball/UseCases/MatchesUseCase.swift
  iOS/Baseball/Baseball/Utils/NotificationCenterExtension.swift
  iOS/Baseball/Baseball/Utils/NotificationToken.swift
  iOS/Baseball/Baseball/Utils/ReusableView.swift
  iOS/Baseball/Baseball/Utils/UIColorExtensions.swift
  iOS/Baseball/Baseball/ViewModels/MatchListViewModel.swift
  iOS/Baseball/Baseball/Views/DimView.swift
  iOS/Baseball/Baseball/Views/GameplayView.swift
  iOS/Baseball/Baseball/Views/MatchCell.swift
  iOS/Baseball/BaseballTests/BaseballTests.swift
  iOS/Baseball/BaseballTests/Info.plist
  iOS/README.md
  iOS/result1.png
Labels: iOS

#52 [iOS] 로그인 화면 구현
  iOS/Baseball/Baseball.xcodeproj/project.pbxproj
  iOS/Baseball/Baseball/Base.lproj/Main.storyboard
  iOS/Baseball/Baseball/Controllers/MatchListViewController.swift
  iOS/Baseball/Baseball/Delegates/MatchListLayout.swift
  iOS/Baseball/Baseball/Resources/Assets.xcassets/ground.imageset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/ground.imageset/ground.png
  iOS/Baseball/Baseball/Resources/Assets.xcassets/mario.imageset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/mario.imageset/mario.png
  iOS/Baseball/Baseball/Views/ConvexLayer.swift
  iOS/Baseball/Baseball/Views/ConvexView.swift
  iOS/Baseball/Baseball/Views/MatchCell.swift
Labels: iOS

#54 [iOS] GitHub OAuth 로그인 구현
  iOS/Baseball/Baseball.xcodeproj/project.pbxproj
  iOS/Baseball/Baseball/Base.lproj/Main.storyboard
  iOS/Baseball/Baseball/Controllers/LogInViewController.swift
  iOS/Baseball/Baseball/Info.plist
  iOS/Baseball/Baseball/Models/Authentication.swift
  iOS/Baseball/Baseball/Networking/APIRouter.swift
  iOS/Baseball/Baseball/Networking/AuthKeys.swift
  iOS/Baseball/Baseball/Networking/Endpoints.swift
  iOS/Baseball/Baseball/Networking/LogInManager.swift
  iOS/Baseball/Baseball/Networking/NetworkManager.swift
  iOS/Baseball/Baseball/UseCases/LoginUseCase.swift
  iOS/Baseball/Baseball/ViewModels/LogInViewModel.swift
  iOS/Baseball/Baseball/Views/LoginView.swift
  iOS/README.md
  iOS/result2.png
Labels: iOS

#53 [iOS] GitHub OAuth를 통한 로그인 기능 구현
  iOS/Baseball/Baseball.xcodeproj/project.pbxproj
  iOS/Baseball/Baseball/Base.lproj/Main.storyboard
  iOS/Baseball/Baseball/Controllers/LogInViewController.swift
  iOS/Baseball/Baseball/Controllers/MatchListViewController.swift
  iOS/Baseball/Baseball/Delegates/MatchListLayout.swift
  iOS/Baseball/Baseball/Info.plist
  iOS/Baseball/Baseball/Models/Authentication.swift
  iOS/Baseball/Baseball/Networking/APIRouter.swift
  iOS/Baseball/Baseball/Networking/AuthKeys.swift
  iOS/Baseball/Baseball/Networking/Endpoints.swift
  iOS/Baseball/Baseball/Networking/LogInManager.swift
  iOS/Baseball/Baseball/Networking/NetworkManager.swift
  iOS/Baseball/Baseball/Resources/Assets.xcassets/ground.imageset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/ground.imageset/ground.png
  iOS/Baseball/Baseball/Resources/Assets.xcassets/mario.imageset/Contents.json
  iOS/Baseball/Baseball/Resources/Assets.xcassets/mario.imageset/mario.png
  iOS/Baseball/Baseball/UseCases/LoginUseCase.swift
  iOS/Baseball/Baseball/ViewModels/LogInViewModel.swift
  iOS/Baseball/Baseball/Views/ConvexLayer.swift
  iOS/Baseball/Baseball/Views/ConvexView.swift
  iOS/Baseball/Baseball/Views/LoginView.swift
  iOS/Baseball/Baseball/Views/MatchCell.swift
  iOS/README.md
  iOS/result2.png
Labels: iOS, review
